### PR TITLE
Update district_roles.yml

### PR DESCRIPTION
**Pull request by JRP-44**
Please see updated names and note change of a few roles.
Thank you

### CODE REVIEW

**Review by genebean — APPROVED** [review]
Looks good to me!

**Comment by genebean** [comment]
This will be live on our site in a minute or two

**Comment by genebean** [comment]
There may be a hiccup with the deployment, I'll check this afternoon

**Comment by JRP-44** [comment]
Gene,I had a couple of notes as the tags you have don’t match structure. Thanks,JamieOn 29 Jan 2024, at 13:45, Gene Liverman ***@***.***> wrote:﻿
There may be a hiccup with the deployment, I'll check this afternoon

**Pull request merged**
